[workspace]
members = [
    "crates/bowser",
    "crates/bowser-cli",
    "xtask",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.3.1"
license = "MIT"
authors = ["Polybase"]
repository = "https://github.com/futex-ai/bowser"
rust-version = "1.89"

[workspace.dependencies]
bowser = { version = "0.3.1", path = "crates/bowser" }
